export const CREATE_TASK_SUCESS = 'CREATE_TASK_SUCESS';
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';

export const DELETE_TASK_SUCESS = 'DELETE_TASK_SUCESS';

export const UPDATE_TASK_SUCESS = 'UPDATE_TASK_SUCESS';

export const FILTER_TASK_SUCESS = 'FILTER_TASK_SUCESS';
